### ISSUE TITLE
How to match [ and ] as individual characters ?

### ISSUE THREAD

**Issue by pgallo725** [p-ranav/glob#17]
Hi, I'm evaluating your library for use in a project of mine. 
I have looked quickly at the wildcards parsing code and it is not clear to me how the user can match the `[` and `]` characters, the documentation is also lacking on this aspect.
From my understanding, the `]` character by itself should work (also a `[` character if there's no following `]` anywhere in the pattern string), `[[]` should work at matching the `[` character, but there's no way of matching `[` OR `]` together. Am I missing something ?

**Comment by p-ranav** [comment]
Thanks for the issue. Yes, it seems the README is lacking in this regard.

Considering the directory tree:

```console
pranav@ubuntu:~/dev/glob$ tree bracket/
bracket/
├── []
│   └── cde.txt
└── [10[20]30]
    └── abc.txt

2 directories, 2 files
```

### To match the directory `[]`:

* Using `[[]` to match the opening bracket '[`
* Using `]` to match the closing bracket ']`

```console
pranav@ubuntu:~/dev/glob$ ./build/standalone/glob -i "bracket/[[]]/*.txt"
"bracket/[]/cde.txt"
```

### To match the directory `[10[20]30]`

Any of the following work:

* Using `[[]` to match the opening bracket `[` and using `]` to match the closing bracket `]`:

```console
pranav@ubuntu:~/dev/glob$ ./build/standalone/glob -i "bracket/[[]10[[]20]30]/*.txt"
"bracket/[10[20]30]/abc.txt"
```

* Using wildcard patterns

```console
pranav@ubuntu:~/dev/glob$ ./build/standalone/glob -i "bracket/[[]*[[]*]*]/*.txt"
"bracket/[10[20]30]/abc.txt"

pranav@ubuntu:~/dev/glob$ ./build/standalone/glob -i "bracket/[[]10????30]/*.txt"
"bracket/[10[20]30]/abc.txt"
```

I intend to keep this library behaving like Python's [glob](https://docs.python.org/3/library/glob.html) for consistency. 

If you have a specific pattern that doesn't to work, please paste it here so I can investigate further. Hope this helps.

**Comment by pgallo725** [comment]
Thanks for your quick answer. This makes sense, and it is in line with my previous understanding.
The only thing I'm missing is if it's possible to have both `[` and `]` characters as options inside a `[ABC]` block (with the meaning of "match either `[` or `]`")... would something like `[ [[] ] ]` work ?

**Comment by p-ranav** [comment]
Yes, my understanding is that you can simply escape the closing bracket with `\]` to help the parser.

```console
pranav@ubuntu:~/dev/glob$ ./build/standalone/glob -i "bracket/[[\]]/*.txt"
"bracket/[]/cde.txt"
```

* Open with `[`
* Match either open bracket `[` or close bracket `\]`
* Close with `]`

**Comment by p-ranav** [comment]
Okay I've run some tests. 

Consider the directory tree:

```console
pranav@ubuntu:~/dev/glob$ tree bracket/
bracket/
├── [
│   └── 123.txt
├── []
│   └── xyz.txt
├── ]
│   └── abc.txt
└── ][
    └── lmn.txt

4 directories, 4 files
```

Now I want to be able to find any or all of these directories with `glob`. 

I would've thought that escaping the closing bracket character would've worked but it didn't. I think this is because the first part of the pattern `[[\]` closes the pattern (which matches with `[` or `\`. The second part of the pattern is just `]`. This is why the directory `[]` (and nothing else) matches here.

```console
pranav@ubuntu:~/dev/glob$ ./build/standalone/glob -i "bracket/[[\]]/*.txt"
"bracket/[]/xyz.txt"
```

An interesting solution to this problem is to check the ASCII table. `[` and `]` are in between `Z` and `_` in the ASCII table. 

![image](https://user-images.githubusercontent.com/8450091/177018103-fc28e122-6f80-4e36-b8d3-5969e11f24be.png)

So we can use ranges to match any character in the table between 2 characters. The following will watch 1 character: either `[`, `^`, or `]`. 

```console
pranav@ubuntu:~/dev/glob$ ./build/standalone/glob -i "bracket/[[-^]/*.txt"
"bracket/]/abc.txt"
"bracket/[/123.txt"
```

We can stack this to match both `[]` and `][` like so:

```console
pranav@ubuntu:~/dev/glob$ ./build/standalone/glob -i "bracket/[[-^][[-^]/*.txt"
"bracket/[]/xyz.txt"
"bracket/][/lmn.txt"
```

**Comment by pgallo725** [comment]
Thanks for the clear explanation. I am closing this issue as resolved.
